# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       sox

# >> macros
# << macros

Summary:    the Swiss Army knife of sound processing programs
Version:    14.4.2
Release:    0
Group:      Applications
License:    GPLv2+ and LGPLv2.1+
URL:        https://sox.sourceforge.net
Source0:    %{name}-%{version}.tar.gz
Source100:  sox.yaml
Source101:  sox-rpmlintrc
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(libpng12)
BuildRequires:  pkgconfig(libpng15)
BuildRequires:  pkgconfig(sndfile)
BuildRequires:  pkgconfig(flac)
BuildRequires:  pkgconfig(flac++)
BuildRequires:  autoconf
BuildRequires:  pulseautdio-devel
BuildRequires:  vorbis-devel
BuildRequires:  opus-devel
BuildRequires:  ogg-devel

%description
SoX is a cross-platform command line utility that can convert various
formats of computer audio files in to other formats. It can also apply
various effects to these sound files, and, as an added bonus, SoX can play
and record audio files on most platforms.

%if "%{?vendor}" == "chum"
PackageName: Template Application
Type: console-application
DeveloperName: Peter G.
DeveloperLogin: nephros
PackagerName: nephros
Categories:
 - Media
 - Audio
 - Utility
Custom:
  Repo: %{url}
Icon: %{url}/sox-logo.png
Screenshots:
 - %{url}/screenshot1.png
Url:
  Homepage: %{url}
  Help: %{url}/Docs/Documentation
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%license LICENSE.GPL
%license LICENSE.LGPL
%{_bindir}/%{name}
%{_libdir}/*.so.*
# >> files
# << files
