# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       sox

# >> macros
# << macros
%define soname 3

Summary:    the Swiss Army knife of sound processing programs
Version:    14.4.2
Release:    0
Group:      Applications
License:    GPLv2+ and LGPLv2+
URL:        https://sox.sourceforge.net
Source0:    %{name}-%{version}.tar.gz
Source100:  sox.yaml
Source101:  sox-rpmlintrc
BuildRequires:  pkgconfig(flac)
BuildRequires:  pkgconfig(flac++)
BuildRequires:  pkgconfig(id3tag)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(libpulse-simple)
BuildRequires:  pkgconfig(ogg)
BuildRequires:  pkgconfig(opus)
BuildRequires:  pkgconfig(sndfile)
BuildRequires:  pkgconfig(vorbis)
BuildRequires:  pkgconfig(vorbisenc)
BuildRequires:  pkgconfig(vorbisfile)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  autoconf
BuildRequires:  libtool
BuildRequires:  libtool-ltdl
BuildRequires:  libtool-ltdl-devel
BuildRequires:  file-devel
BuildRequires:  bzip2

%description
SoX is a cross-platform command line utility that can convert various
formats of computer audio files in to other formats. It can also apply
various effects to these sound files, and, as an added bonus, SoX can play
and record audio files on most platforms.

%if "%{?vendor}" == "chum"
PackageName: Template Application
Type: console-application
DeveloperName: Peter G.
DeveloperLogin: nephros
PackagerName: nephros
Categories:
 - Media
 - Audio
 - Utility
Custom:
  Repo: %{url}
Icon: %{url}/sox-logo.png
Screenshots:
 - %{url}/screenshot1.png
Url:
  Homepage: %{url}
  Help: %{url}/Docs/Documentation
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%package -n lib%{name}%{soname}
Summary:    Libraries for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n lib%{name}%{soname}
%{summary}.

%package doc
Summary:    Documentation for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-stack-protector \
    --with-distro="Sailfish OS (%{vendor})" \
    --without-ladspa \
    --without-alsa \
    --without-oss

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
./README.sh
# << install post

%post -n lib%{name}%{soname} -p /sbin/ldconfig

%postun -n lib%{name}%{soname} -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%license LICENSE.GPL
%license LICENSE.LGPL
%{_bindir}/*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_libdir}/*.so
%{_libdir}/*/*.pc
%{_includedir}/*.h
%{_mandir}/man3/*
# >> files devel
# << files devel

%files -n lib%{name}%{soname}
%defattr(-,root,root,-)
%{_libdir}/*.so.*
# >> files lib%{name}%{soname}
# << files lib%{name}%{soname}

%files doc
%defattr(-,root,root,-)
%doc AUTHORS COPYING ChangeLog NEWS README.sh src/monkey.wav
%{_mandir}/man1/*
%{_mandir}/man7/*
# >> files doc
# << files doc
